#!/usr/bin/env python3
import argparse

import gymnasium as gym
import numpy as np

parser = argparse.ArgumentParser()
# These arguments will be set appropriately by ReCodEx, even if you change them.
parser.add_argument("--episodes", default=1000, type=int, help="Training episodes.")
parser.add_argument("--recodex", default=False, action="store_true", help="Running in ReCodEx")
parser.add_argument("--seed", default=42, type=int, help="Random seed.")
# If you add more arguments, ReCodEx will keep them with your default values.
parser.add_argument("--gamma", default=1, type=float, help="Discounting factor.")

''' 
The goal is to estimate (evaluate) the value function of target policy π, which uniformly chooses either action 1 or 2, 
using episodes generated by the behavior policy b, which uniformly randomly chooses any of the 4 actions. Use weighted 
importance sampling to perform the estimation. 

Useful for example for offline policy evaluation (data are already collected with some behavior policy, but we want 
to evaluate a different target policy), or for expert trajecories
'''

def main(args: argparse.Namespace) -> np.ndarray:
    # Create the environment.
    env = gym.make("FrozenLake-v1")
    env.reset(seed=args.seed)
    env.action_space.seed(args.seed)

    # Set the random seed.
    np.random.seed(args.seed)

    # Behavior policy is uniformly random.
    # Target policy uniformly chooses either action 1 or 2.
    V = np.zeros(env.observation_space.n) # Value function
    C = np.zeros(env.observation_space.n) # Importance weights cumulative sum

    for _ in range(args.episodes):
        state, done = env.reset()[0], False

        # Generate one episode
        episode = []
        while not done:
            action = env.action_space.sample() # Behavior policy: choose a random action
            next_state, reward, terminated, truncated, _ = env.step(action) # make a step
            done = terminated or truncated
            episode.append((state, action, reward)) # episode = [(s0,a0,r1),(s1,a1,r2),...]
            state = next_state

        # TODO: Update V using weighted importance sampling.
        W = 1.0
        G = 0.0
        for step in reversed(episode):
            s, a, r = step

            if a == 1 or a == 2: # If the action is consistent with the target policy
                W *= 0.5 / 0.25 # (target_prob / behavior_prob)
            else:
                break # If the action is not consistent with the target policy, we can stop updating for this episode

            G = r + args.gamma * G
            
            C[s] += W
            V[s] += (W / C[s]) * (G - V[s]) # Update V(s) using the weighted importance sampling formula

    return V


if __name__ == "__main__":
    main_args = parser.parse_args([] if "__file__" not in globals() else None)

    value_function = main(main_args)

    # Print the final value function V
    for row in value_function.reshape(4, 4):
        print(" ".join([f"{x:5.2f}" for x in row]))
